### PR TITLE
Fixed issue "Custom Highlights"

### PR DESCRIPTION
**Pull request by Mitchdev**
Fixed issue #46

### CODE REVIEW

**Review by 11k — CHANGES_REQUESTED** [review]
Thanks a lot! Just need you to bump the patch version number and this is ready for merging.

**Comment by Mitchdev** [comment]
Done. @11k

**Comment by 11k** [comment]
Sorry for the complete 180, but can you force push with your original commit only to get rid of the merge and version bump commits. We're going to handle version bumping differently going forward to make things easier for contributors.

**Comment by Mitchdev** [comment]
No worries, There you go. @11k

**Pull request merged**
