### PR TITLE
Bug fixes with setting cookie values.

### PR DESCRIPTION
**Pull request by sheriffoftiltover**
If the cookie request header does not already exist, an error is thrown for attempting to call .replace on null.

Additionally, the bakeCookies function assumed that the sid would already exist in the cookie, which is not necessarily true.

### CODE REVIEW

**Review by 11k — COMMENTED** [review]
I appreciate the SID cookie fix, but I'm on the fence about merging in these other changes. Unless I'm missing something, they seem inconsequential and don't really address any issues with user management. The only thing I noticed is the addition of `onJOIN`. `onDISPATCH` already handles user joins, so now it's happening twice for each `JOIN` event.

**Comment by JakeFromStateCS** [comment]
@11k Yeah, that's my fault, I forgot to make a new branch before I started working on other fixes.

Go ahead and close this and I'll open another pr with specifically the cookie fixes.

**Comment by sheriffoftiltover** [comment]
@11k Yeah, that's my fault, I forgot to make a new branch before I started working on other fixes.
Go ahead and close this and I'll open another pr with specifically the cookie fixes.

**Comment by 11k** [comment]
You can just force push away the second commit, should be fine.

**Review by 11k — APPROVED** [review]

**Pull request merged**
