### PR TITLE
update EmbedUrlFormatter.js

### PR DESCRIPTION
**Pull request by mia-z**
- update bigscreen embedurl regex to match youtube embeds with a timestamp

Will match #youtube/57VVjxsK_cU&t=123s

Specifically, will look for &t=, followed by digits, followed by an s
&t= + 123 + s

Seen someone in chat attempt to link an embed this way and thought it could be something worth adding.

### CODE REVIEW

**Comment by 11k** [comment]
All YouTube hash links disappear for me with this change. This doesn't happen for you? It looks like the YouTube hash link regex is outside the second capture group now, which is probably why.

**Comment by mia-z** [comment]
Odd. I've tested it with both regexr and regex101 and they're both capturing as they should

image

image


It's inside the same capture group, I just added an extra alternative which checks for &t=\ds -- moved into it's own alternative since this wouldnt apply to rumble/vimeo/twitch links.

**Comment by 11k** [comment]
Would you mind testing in production chat using the dev server? If it works for you there, then I know it's a problem on my end and I'll troubleshoot more. Make sure you have the latest dependencies installed with `npm ci`.

**Comment by mia-z** [comment]
You're right - it completely removes the embed, and leaves the time query, odd. I just assumed the Regex would work since the above capture groups were correct in test. Any idea why this would be happening?

**Comment by 11k** [comment]
I disagree that the capture groups are unchanged and think that's the source of the issue. [This call](https://github.com/destinygg/chat-gui/blob/master/assets/chat/js/formatters/EmbedUrlFormatter.js#L24-L27) references capture groups in the replacement string, which doesn't work properly now because they're different.

**Comment by mia-z** [comment]
Completely correct - there was indeed a bracket I missed. 

I tried rearranging it a little and put the youtube inside the capture group 

`(^|\s)((#twitch(-vod|-clip)?|#vimeo|#rumble)\/[\w-]{3,64}|#youtube\/[\w-]{3,64}(&t=(\d+)s)?|#facebook\/\d{10,20}\/videos\/\d{10,20})`

But now it doesnt seem to capture the timestamp and I cant figure out why. It captures the #youtube/videoid as normal, though.

**Comment by Mitchdev** [comment]
I think I've found the problem.

https://github.com/destinygg/chat-gui/blob/0080cf29b4691ac512f88a5b23405d6cd624e9ff/assets/chat/js/formatters/EmbedUrlFormatter.js#L16

the message is sterilized so the output (str) for `#youtube/lcCcXEkXeqA&t=2s` is actually `#youtube/lcCcXEkXeqA&amp;t=2s`
therefore you need to change `&t=` to `&amp;t=`

**Pull request closed without merging**
