### PR TITLE
Emotes inline with autocomplete.

### PR DESCRIPTION
**Pull request by Mitchdev**
Shows the emote next to the text in autocomplete menu.
image

### CODE REVIEW

**Comment by razr22** [comment]
Would it be better if the emotes were rendered in the comment rather than in the autocomplete suggestions? It would save autocomplete suggestions screen space (fit more suggestions in the same space) and the user would be able to view the composed comment before sending.

**Comment by hlwenk** [comment]
Would it be better if the emotes were rendered in the comment rather than in the autocomplete suggestions? It would save autocomplete suggestions screen space (fit more suggestions in the same space) and the user would be able to view the composed comment before sending.

**Comment by Mitchdev** [comment]
@hlwenk are you talking inside the textbox like how discord has it?

I've looked into this is seems like discord and other websites that do this do it via modules such as slatejs or draftjs which requires react or a similar framework to work, which chat-gui isn't in.
I have attempted to make my own version.

https://user-images.githubusercontent.com/13901269/211141392-10077c42-c8c6-45c6-afa2-8673b837019e.mp4

It's riddled with bugs and use cases I haven't found yet but the core idea is there.
Would like to hear your thoughts @11k

**Comment by Mitchdev** [comment]
#106

**Pull request closed without merging**
